fail_fast: true
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.670'
    hooks:
    - id: mypy

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    - id: autopep8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
        id: flake8

