service: python-service-template

plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: /
