.iamRoleStatements: &default_roles
  - Effect: Allow
    Action:
      - secretsmanager:GetSecretValue
    Resource:
      Fn::Join:
        - ":"
        - - "arn:aws:secretsmanager"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "*"
  - Effect: Allow
    Action:
      - ssm:GetParameters
      - ssm:DescribeParameters
      - ssm:GetParameter
      - ssm:PutParameter
    Resource:
      Fn::Join:
        - ":"
        - - "arn:aws:ssm"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "*"
  - Effect: Allow
    Action:
      - kms:Decrypt
    Resource:
      Fn::GetAtt:
        - ConfigKey
        - Arn

dev:
  iamRoleStatements: *default_roles
staging:
  iamRoleStatements: *default_roles
production:
  iamRoleStatements: *default_roles
